resources:
  - name: myAppRepo1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github             # Change to your integration
      path: raksha78/pipeTest  
pipelines:
  - name: my_pipeline
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo1
        execution:
          onExecute:
            - echo $MY_MESSAGE
#             - sleep 15m
 
