resources:
  - name: myAppRepo2
    type: GitRepo
    configuration:
      gitProvider: raksha78_github             # Change to your integration
      path: raksha78/pipeTest  
pipelines:
  - name: pipe_test
    steps:
      - name: step_check
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo2
          integrations:
            - name: slack_extension
            - name: art_v
            - name: bb_extension
            - name: raksha78_bbs
            - name: DR_extension
            - name: GC_extension
            - name: generic_extension
            - name: gL_extension
            - name: git_v
            - name: Kuber_extension
        execution:
          onExecute:
            - printenv
            - ls
